import React, { Component } from 'react'
import { Col, Container, Row, Card, CardBody } from 'reactstrap'
import ReactGA from 'react-ga'

export class TermsOfServiceComponent extends Component {
  constructor (props) {
    super(props)
    ReactGA.initialize('UA-132063819-1')
    ReactGA.pageview(window.location.pathname + window.location.search)
  }

  render () {
    return (
      <Container className='dashboard'>
        <Row>
          <Col xs={12} md={12} lg={12} xl={12}>
            <h3 className='page-title'>Terms of Service</h3>
          </Col>
        </Row>
        <Row>
          <Col xs={12} md={12} lg={12} xl={12}>
            <Card>
              <CardBody id='terms-of-service'>
                <em>Version 1.0 Published 2019-01-13</em>
                <h4>A. Introduction</h4>
                <p>This Agreement between the owner-operator of this instance of GrinPool;,
                  &quot;<strong>we</strong>&quot;, &quot;<strong>us</strong>&quot;&quot; or &quot;<strong>our</strong>&quot;) and
                  you (referred to in this Agreement as &quot;<strong>Participant</strong>&quot;, &quot;<strong>you</strong>&quot;,
                  or &quot;<strong>your</strong>&quot;), applies to your participation in the GrinPool GRIN mining pool
                  service, the registration and administration.
                  This Agreement and associated Participant FAQ set out how the mining pool service works and describe any
                  associated rights and responsibilities. Any instructions, guidance and similar information found on the Website
                  also apply to your use of the mining pool service.</p>
                <h4>B. Registration and Binding Agreement</h4>
                <ol>
                  <li>By applying to register, you are making an offer to enter into an agreement on the terms set out in this
                    Agreement. Once submitted, you may not withdraw your offer.</li>
                  <li>Only we can decide whether applications will be accepted. If your application is accepted, this Agreement
                    will be a legal and enforceable agreement between you and us.</li>
                  <li>GrinPool reserves the right to change this Agreement from time to time as it sees fit, providing such notice
                    as is required by applicable law and the User’s continued use of the Service will signify the User’s
                    acceptance of any adjustment to these terms. Should User not accept such changes, User should not continue to
                    use the Service.</li>
                  <li>If there is ever a conflict between this Agreement, and the Participant FAQ or other instructions, guidance
                    and similar information found on the Website, this Agreement will take priority.</li>
                </ol>
                <h4>C. Definitions</h4>
                <ol>
                  <li>In this Agreement:</li>
                  <li>&quot;<strong>Account</strong>&quot; means your personal access to the Service, described further in
                    section 2;</li>
                  <li>&quot;<strong>Actual Contribution</strong>&quot; means the product of multiplying the Contribution by the Mining
                    Period, as more particularly described in the Participant FAQ.</li>
                  <li>&quot;<strong>Cryptocurrencies</strong>&quot; means distributed, decentralized peer-to-peer digital currencies:</li>
                  <li>&quot;<strong>Contribution</strong>&quot; means the contribution by a Participant of the Graph Rate of their Mining
                    Rigs to the Mining Pool.</li>
                  <li>&quot;<strong>Gross Payout</strong>&quot; means the amount generated by the applicable Payout Algorithm, prior to
                    netting out the Pool Fee, as applicable, to produce the actual, net Payout.</li>
                  <li>&quot;<strong>Graph Rate</strong>&quot; is the mining power of each Mining Rig, measured by its ability to mine the
                    Cuckatoo and Cuckaroo family of mining algorithms</li>
                  <li>&quot;<strong>including</strong>&quot; or &quot;<strong>includes</strong>&quot; means including without limitation.</li>
                  <li>&quot;<strong>Mining Period</strong>&quot; means the period during which the Mining Rig was actually mining in
                    accordance with its Graph Rate, and for greater certainty excludes any downtime of the applicable Mining Rig.</li>
                  <li>&quot;<strong>Mining Pool</strong>&quot;, as further described herein and in the Participant FAQ, means
                    the collective GRIN mining pool operated by GrinPool, into which each Participant makes their
                    Contribution from the Participant Mining Rigs and pays the Pool Fee, in consideration for which GrinPool pays
                    Participant the Payout based on the Payout Algorithm.</li>
                  <li>&quot;<strong>GRIN</strong>&quot; means the cryptocurrency GRIN, which is an instance of the MimbleWimble technology,
                    and whose core information can be found at https://www.GitHub.com/mimblewimble/grin</li>
                  <li>&quot;<strong>Mining Rig</strong>&quot; means the computer hardware owned by the Participant that is used
                    to mine Cryptocurrencies.</li>
                  <li>&quot;<strong>Participant FAQ</strong>&quot; means the participant guide</li>
                  <li>&quot;<strong>Payout</strong>&quot; is the periodic manual or automated deposit to your Wallet, as calculated in accordance
                    with the Payout Algorithm.</li>
                  <li>&quot;<strong>Payout Schedule</strong>&quot; means the schedule of automated Payout dates, as set out by GrinPool in the
                    Participant FAQ, and as may be changed by GrinPool from time to time in accordance with this Agreement. It may also
                    periodically be suspended in favor of manual payout options.</li>
                  <li>&quot;<strong>Pool Fee</strong>&quot; means the percentage fee applicable to the PPLNSG payout schedule as set
                    out in the Participant FAQ and described in Section F.1 of this Agreement.</li>
                  <li>&quot;<strong>Service</strong>&quot; has the meaning ascribed in Section D.1. of this Agreement.</li>
                  <li>&quot;<strong>Wallet</strong>&quot; means a software program in which Cryptocurrencies are stored, as licensed to and
                    operated by the Participant.</li>
                </ol>
                <h4>D. Service and Contribution</h4>
                <ol>
                  <li>GrinPool shall provide access to the Mining Pool and pay the applicable Payout to each Participant (the &quot;<strong>Service</strong>&quot;)
                    in consideration for the Participant (a) providing their Actual Contribution to the Mining Pool, and (b)
                    payment of the Pool Fee, in each case in accordance with this Agreement.</li>
                  <li>The Participant FAQ outlines how each Participant can make a Contribution.</li>
                </ol>
                <h4>E. Registration</h4>
                <ol>
                  <li>You may only apply to register as a Participant if:</li>
                  <li>you have the right, authority, and capacity to enter into this Agreement and to abide by all of the terms
                    and conditions set forth herein;</li>
                  <li>you are of the age of majority in the applicable jurisdiction; and</li>
                  <li>To register as a Participant, you must create an Account using GrinPool&apos;s login / registration page.</li>
                  <li>Your username and password will be allocated to you if you successfully apply for registration as a
                    Participant. You will need your username and password to access the Service. In particular, your username and
                    password are personal to you and must not be disclosed to any other person. Note that GrinPool admin will
                    never ask you to disclose your password. Any message the Participant receives or website that he/she visits
                    that asks for the password, other than the Website, should be reported to GrinPool. The Participant is
                    responsible for maintaining the confidentiality of his/her Account’s credentials, including, but not limited
                    to, username, password, Wallet address, and all activity made through the Account.</li>
                  <li>You will need to enter at least one Wallet address in order to receive automated Payouts.</li>
                  <li>Each Participant is limited to one Account.</li>
                  <li>By submitting the registration application, the Participant confirms that they are not acting for the
                    benefit of any other person or entity not identified on such application.</li>
                  <li>If you lose access to your Account, GrinPool may ask you to provide certain types of data, including
                    mining statistical data and / or recent payout amounts.</li>
                </ol>
                <h4>F. Pool Fee</h4>
                <ol>
                  <li>We provide the platform on which the Mining Pool operates, in return for which we charge a Pool Fee to each
                    Participant, which includes maintenance and electricity costs and other expenditures required to render the
                    Service. The Pool Fee is applied to each Payout and is non-refundable.</li>
                  <li>Participant acknowledges and agrees that (a) GrinPool must receive the payment of each Pool Fee in order for
                    GrinPool to continue to operate the Platform, (b) given that the Pool Fee is calculated as a percentage of the
                    Gross Payout, should the value of the Gross Payouts decline (including due to factors such as currency
                    fluctuation and increased regulation), the total Gross Payouts of all of the participants may be insufficient
                    to generate the necessary Pool Fees, and (c) in that case, GrinPool may terminate this Agreement upon prior
                    written notice to the Participant.</li>
                  <li>GrinPool may, from time to time, upon notice waive the Pool Fee for promotional and marketing purposes, in
                    which case the Payout shall be equal to the Gross Payout during the period of such waiver.</li>
                </ol>
                <h4>G. Risk Notice</h4>
                <ol>
                  <li>Actions with Cryptocurrencies carry inherent risks. Cryptocurrencies may not be appropriate for everyone.
                    By applying to be a Participant, you confirm that you have learned about Cryptocurrencies to ensure that they
                    are appropriate for you, and accept the risks.</li>
                  <li>Like all currencies, there are disadvantages to using Cryptocurrencies. Some of the risks particular to Cryptocurrencies include:<ol>
                    <li>currency fluctuation &#8211; the price of GRIN may fall sharply and may even fall to zero;</li>
                  </ol>
                  </li>
                  <li>transactions with Cryptocurrencies may be unconfirmed for a period of time. Although very unlikely, some
                    GRIN transactions may never be confirmed &#8211; GRIN transactions which are unconfirmed
                    are not completed;</li>
                  <li>transactions with Cryptocurrencies are irreversible &#8211; if you send any amount of any GRIN to
                    the wrong person, you may be unable to recover those funds;</li>
                  <li>Cryptocurrencies may be lost if you lose or forget any PINs or passwords necessary to access and spend
                    those Cryptocurrencies;</li>
                  <li>unknown technical defects inherent in Cryptocurrencies; and</li>
                  <li>new regulation which impacts the use of Cryptocurrencies.</li>
                  <li>You must not mine, buy, sell, exchange, hold, own or otherwise use or exploit Cryptocurrencies in any way
                    which is prohibited by the laws or regulations which apply to you.</li>
                  <li>Due to the fact that Cryptocurrencies are unregulated and decentralized, their value is not insured by any
                    legal entities. The value of any amount of any GRIN is subject to change by GrinPool due to a number
                    of factors out of the control of GrinPool. These factors include but are not limited to changes of mining
                    difficulty and/or other mining parameters/properties, fluctuating price (in fiat currency to GRIN
                    exchange rate, such as USD/GRIN) of Cryptocurrencies. You understand and agree that the value of any Payout,
                    and any amount of mined GRIN, may lose all value at any moment of time due to the nature of
                    Cryptocurrencies.</li>
                  <li>You understand that you are solely responsible for management of the Cryptocurrencies in your Wallet.</li>
                  <li>Any information related to GRIN and GRIN mining that is/was posted, published and/or
                    provided by GrinPool via any channel of communication (including but not limited to: on the Website, in via
                    email newsletter, in social media) is informational only and is subject to change.</li>
                  <li>There is risk associated with hacking the Service, including denial of services attacks, malware attacks,
                    mining attacks or consensus-based attacks.</li>
                  <li>There are risks associated with usage of the Service through internet including the failure of hardware,
                    software, configuration and internet connections. Without limitation GrinPool will not be responsible for any
                    configuration, connection or communication failures, disruptions, errors, distortions or delays Participant
                    may experience when using GrinPool Service, howsoever caused.</li>
                  <li>IT IS NOT POSSIBLE FOR US TO STATE DEFINITIVELY HOW MANY GRIN UNITS, IF ANY, WILL BE MINED DURING
                    ANY PAYOUT PERIOD.</li>
                  <li>Participant acknowledges and agrees that the foregoing is informational only and is not an exhaustive list
                    of all risks – in addition to the risks disclosed above, there are risks that GrinPool cannot foresee.</li>
                </ol>
                <h4>H. Term and Termination</h4>
                <ol>
                  <li>Each Participant may terminate the Agreement, and close their Account at any time, following settlement of
                    any pending transactions.</li>
                  <li>Each Participant also agrees that GrinPool may, by giving notice, at its sole discretion terminate their
                    access to the Service and to their Account, delay or remove hosted content, and take technical and legal
                    steps to terminate the Participant’s use of the Service if the Participant is in breach of the Agreement.</li>
                  <li>GrinPool may, by giving notice, at its sole discretion terminate access to the Service for more than one or
                    all participants</li>
                  <li>Accounts which are inactive for longer than twelve (12) months (no mining activity) may be deleted after
                    three email warnings. Remaining Payout or shares associated with the Account will be considered as a donation
                    to the Mining Pool with no further attribution or obligation to Participant.</li>
                  <li>Upon termination, the Participant Account will be closed, and access to the Service revoked, and any Payout
                    accrued by the effective date of such termination paid into the Wallet of the Participant.</li>
                  <li>Without limiting any other rights we have, we may suspend access to your Account, and the Service, if you
                    breach this Agreement, or if we have grounds to suspect that you are using the Service fraudulently or
                    improperly until you are able to demonstrate to our satisfaction your identity and that no fraud or
                    impropriety has occurred or been attempted.</li>
                  <li>If you become aware of or suspect another person’s breach of this Agreement or any fraud or impropriety in
                    connection with the Service, you must contact us immediately.</li>
                </ol>
                <h4>I. Use of Your Account</h4>
                <ol>
                  <li>You may only participate in the Mining Pool for your own benefit. By using the Service you confirm that you
                    are not acting for the benefit of any other person or entity other than as expressly identified on your
                    registration application.</li>
                  <li>We are entitled to assume that any use of your Account is made by you. You are solely responsible and
                    liable for any use of the Service under your Account or any other use of your username and password.</li>
                  <li>You may only hold one Account. If you forget your username or password, you can use the password recovery
                    option or contact GrinPool support.</li>
                  <li>DO NOT SHARE YOUR USERNAME AND PASSWORD WITH ANY OTHER PERSON OR ALLOW ANY OTHER PERSON TO USE YOUR
                    ACCOUNT. WE ARE NOT LIABLE FOR ANY IMPROPER USE OF YOUR USERNAME, PASSWORD OR ACCOUNT BY YOU OR ANY OTHER
                    PERSON. IF YOU HAVE REASONS TO ASSUME THAT ANY OTHER PERSON KNOWS YOUR USERNAME OR PASSWORD, OR THAT YOUR
                    ACCOUNT HAS BEEN USED BY ANY OTHER PERSON, YOU MUST INFORM US IMMEDIATELY.</li>
                </ol>
                <h4>J. Payout</h4>
                <ol>
                  <li>In consideration for the Contribution, GrinPool shall pay Participant a Payout in accordance with the Payout
                    Schedule, the amount of which is determined by the Payout Algorithm. GrinPool reserves the right to change the
                    Payout Algorithm at any time in accordance with this Agreement.</li>
                  <li>In the case of any dispute regarding the amount of the Payout, the calculation of the Payout determined by
                    GrinPool acting reasonably, shall govern.</li>
                  <li>The Payout will be transferred to your Wallet. Participant is solely responsible for the accuracy of the
                    Wallet address for the purpose of the Payout.</li>
                  <li>Neither the Mining Pool, nor your Account, are an e-wallet or a bank for your coins. GrinPool is not
                    responsible for any loss of coins from your Wallet. It is your responsibility to configure your Account so
                    that the Payout may be transferred to your own Wallet.</li>
                  <li>It is the responsibility of the Participant to determine what, if any, taxes apply to the transactions it
                    completes in connection with the Service, and to report and remit the correct tax to the appropriate tax
                    authority. Participant agrees that GrinPool is not in any case and under no conditions responsible for
                    determining whether taxes apply to these transactions.</li>
                </ol>
                <h4>K. Restrictions and Obligations</h4>
                <ol>
                  <li>You agree to comply with all applicable laws and regulations, this Agreement and all rules applicable to
                    the use of the Service.</li>
                  <li>You agree not to falsely describe or otherwise misrepresent yourself in any dealings with GrinPool.</li>
                  <li>You are not allowed to abuse any campaigns, promotions or discounts provided from time to time in
                    connection with the Service.</li>
                  <li>You are not allowed to use any means to mask your internet traffic and IP address (such as Proxy, Tor, VPN
                    and others).</li>
                  <li>Each Participant is prohibited from using the Mining Pool in any way in connection with Multi-Level
                    Marketing (MLM) and/or High-Yield Investment Projects (HYIP) systems.</li>
                  <li>You are strictly forbidden to use or exploit errors in design of the Website, the Service and/or all and
                    any of their parts, features which have not been documented, and/or &quot;program bugs&quot; for
                    commercial/personal gain or as means to disrupt and/or destabilize the Service. If you encounter such an
                    error by accident, you are required to report your findings to GrinPool via private a communications channel</li>
                  <li>You are prohibited from directly or indirectly using botnets. Accounts with a large amount of participants
                    connecting from different IP addresses may be suspended without prior notice.</li>
                  <li>Participants suspected of dishonest, fraudulent or illegal activities may be banned without prior notice.</li>
                  <li>The uptime of the Service is not guaranteed; maintenance and downtime may be required at times.
                    Participants are responsible for configuring their Mining Rigs so that they will automatically reconnect or
                    switch to a backup pool in the case of downtime.</li>
                  <li>For greater certainty, maintenance of each Mining Rig of the Participant is the responsibility of the
                    Participant.</li>
                  <li>You agree not to use the Service in any way which is unlawful, may give rise to civil or criminal liability
                    for GrinPool, or may bring GrinPool into disrepute.</li>
                </ol>
                <h4>L. Indemnity</h4>
                <ol>
                  <li>You hereby agree to indemnify and hold GrinPool, its affiliates and their respective officers, employees,
                    agents and providers harmless from and against any and all liability and costs (including reasonable legal
                    fees) incurred by the Indemnified Parties in connection with any claim arising out of:</li>
                  <li>any fraud or fraudulent misrepresentation, or negligence or negligent misrepresentation, you commit;</li>
                  <li>any inaccuracy or defect of any of the information you have provided to us;</li>
                  <li>any breach of applicable law or regulation you commit;</li>
                  <li>any breach by you of this Agreement; and</li>
                  <li>your use of the Service, or any use of your Account (whether or not such use was by you).</li>
                  <li>We reserve the right, at our own expense, to assume the exclusive defense and control of any matter
                    otherwise subject to indemnification by you. You shall cooperate with us, at your own expense, in the defense
                    of any claim.</li>
                </ol>
                <h4>M. Liability</h4>
                <ol>
                  <li>We provide and maintain the Website and the Service on an &quot;AS IS&quot; and &quot;AS
                    AVAILABLE&quot; basis.</li>
                  <li>To the maximum extent permitted by applicable law, we give no and actively disclaim all other
                    representations, warranties, covenants and conditions, whether express, implied, statutory or otherwise, in
                    connection with the Service, including merchantability, suitability, reliability, availability, timeliness,
                    accuracy, satisfactory quality, fitness for a particular purpose or quality, title and non-infringement, and
                    without limitation actively exclude all liability for:</li>
                  <li>accuracy, currency or validity of information and material contained within and/or provided by the Website
                    and otherwise by the Service, in email newsletters and social media, noting without limitation that
                    occasional technical disruptions and human error may affect the Service and result in misrepresentation of
                    content or miscommunication;</li>
                  <li>any change in the exchange rate of any GRIN;</li>
                  <li>any change in the difficulty of mining;</li>
                  <li>any changes in applicable law or regulation, or the acts of any legislator or regulator;</li>
                  <li>any interruptions to or error of the Website or the Service otherwise or other communications network;</li>
                  <li>any amount or kind of loss or damage due to viruses or other malicious software that may infect a
                    user&#8217;s computer equipment, software, data or other property caused by accessing the Service;</li>
                  <li>any failure of the Service to be uninterrupted, harmless, secure or not corrupt or damaged, meet
                    Participant’s requirements, achieve any intended results, be compatible or work with any other software,
                    applications, systems or services, meet any performance standard or be error free, or to correct any errors
                    or defects; and</li>
                  <li>all other representations, warranties, covenant and conditions which, but for this notice, would have
                    effect.</li>
                  <li>We will not be liable in any amount for any failure to perform any obligation under this Agreement if that
                    failure is caused by the occurrence of an event beyond our reasonable control.</li>
                  <li>GrinPool, its affiliates and their respective officers, employees and agents to the maximum extent permitted
                    by applicable law, whether in contract, warranty, tort (including negligence, whether active, passive or
                    imputed), product liability, strict liability or other theory, arising out of or relating to the use of the
                    Service, or inability to use the Service or under any other document or agreement executed and delivered in
                    connection herewith or contemplated hereby, will not be liable to Participant or anyone else, for any damages
                    of any kind, including direct, consequential, incidental, special or indirect damages including lost profits,
                    losses or damages; loss of anticipated savings; loss of business opportunity and management time; loss of
                    goodwill; loss of GRIN arising as a result of any of your acts or omissions or those of any third
                    party; loss arising out of or in connection with: any defect or insecurity in any systems you use to store or
                    transmit GRIN or to access or use the Service; any inaccurate or incomplete information you
                    provide, including Wallet addresses; any changes to the amount of GRIN awarded to Participants; any
                    changes to the regulatory, legislative or technical environment applicable to Cryptocurrencies; the acts or
                    omissions of any bank or provider of banking services; or any change in the value of GRIN howsoever
                    arising (including as a result of the acts or omissions of GrinPool).</li>
                  <li>You agree that the allocation of liability set out in this Agreement is reasonable and appropriate in light
                    of the nature of the Service.</li>
                </ol>
                <h4>N. Intellectual Property</h4>
                <ol>
                  <li>GrinPool retains all copyright and other intellectual property rights in connection with the Service,
                    including inventions, discoveries, knowhow, processes, marks, methods, compositions, formulae, techniques,
                    information and data, whether or not patentable, copyrightable or protectable in trademark, and any
                    trademarks, copyrights or patents based thereon over all content and other materials contained on Site or
                    provided in connection with the Service, including, the GrinPool logo and all designs, text, graphics,
                    pictures, information, data, software, source code, as well as the compilation thereof, sound files, other
                    files and the selection and arrangement thereof. These material is protected by copyright laws and other
                    intellectual property right laws.</li>
                  <li>GrinPool hereby grants User a limited, nonexclusive, revocable, non-transferrable and non-sublicensable
                    license to access and use the Service for the personal or internal business use of the Participant (the &quot;<strong>Purpose</strong>&quot;).
                    Such license is subject to this Agreement and does not permit any resale, the distribution, public
                    performance or public display, modifying or otherwise making any derivative uses, use, publishing,
                    transmission, reverse engineering, participation in the transfer or sale, or any way exploit any of the
                    copyrighted work and other intellectual property other than for the Purpose. This granted license will
                    automatically terminate if GrinPool suspends or terminates access to the Account or the Service.</li>
                </ol>
                <h4>O. General</h4>
                <ol>
                  <li>Our failure to enforce any term of this Agreement does not constitute our waiver of that term.</li>
                  <li>If any part of this Agreement is found to be unenforceable, it will be amended to the minimum extent
                    necessary to make it enforceable and the remainder of the provisions will remain in full force and effect.</li>
                  <li>Without limitation, no representation, warranty or covenant is made as to whether the Website or the
                    Service complies with the laws of any jurisdiction.</li>
                  <li>The parties submit to the exclusive jurisdiction of the courts of Antigua and Barbuda. These terms of
                    service are subject to and interpreted in accordance with the laws of Antigua and Barbuda.</li>
                  <li>The Website may be presented in multiple languages. In the case of a conflict between translations, the
                    English version will prevail.</li>
                  <li>GrinPool will be entitled to assign and otherwise transfer the Agreement. You may not assign and otherwise
                    transfer the Agreement.</li>
                </ol>
              </CardBody>
            </Card>
          </Col>
        </Row>
      </Container>
    )
  }
}
